from __future__ import annotations


MENU_SCENE = 0
GAME_SCENE = 1
RESULT_SCENE = 2
PAUSE_SCENE = 3
OPTIONS_SCENE = 4
MODES_SCENE = 5
CAREER_SCENE = 6
ACHIEVEMENTS_SCENE = 7
CHALLENGE_SCENE = 8
RUN_HISTORY_SCENE = 9
THEMES_SCENE = 10
JOURNAL_SCENE = 11
EXIT_SCENE = -1
